# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
SCUsersBundle:
    resource: '@SCUsersBundle/Resources/config/routing/security.xml'
    prefix: /openid
