security:
    factories: 
      - "%kernel.root_dir%/../vendor/bundles/Fp/OpenIdBundle/Resources/config/security_factories.xml"
    providers:        
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^(/demo/secured/|/)
            openid:       true
            form_login:
                provider: fos_userbundle
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /
            logout:       true
            anonymous:    ~

    access_control:
        - { path: ^/openid/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
